### ISSUE TITLE
Search engine dialog causes overlay that persists until tapped/clicked

### ISSUE THREAD

**Issue by patarapolw** [jerryhcooke/smouldering_durtles#5] opened 2023-05-11 05:39 UTC
I can't add Search engine 3-5, as well as can't edit the preset 1-2 (Wiktionary, Jisho).

<img src="https://github.com/jerryhcooke/smouldering_durtles/assets/21255931/aaa89cbc-7ae8-414b-bb52-d0573933b5eb" width="300" alt="Can't edit Search engine" />

<img src="https://github.com/jerryhcooke/smouldering_durtles/assets/21255931/0bd6a032-1629-4221-8111-5738cb9b9527" width="300" alt="Comparing with Flaming Durtles" />

**Comment by jerryhcooke** [comment] 2023-05-11 08:59
Hi! Thanks for letting me know about this, I'll take a look at what can be done to remove it once I've fixed the current issue with the review timeline. 

Can I ask, is this same behaviour present in Flaming Durtles? Just trying to work out if it's caused by something I've done

**Comment by patarapolw** [comment] 2023-05-11 10:21
The second image is from Flaming Durtles, which works OK.

First image is Smouldering. This one only has dark overlay, but no dialog and input box.

**Comment by jerryhcooke** [comment] 2023-05-12 00:48
Confirming that this issue is resolved in v1.0.1 - issue was due to depreciated fragment handling.

![image](https://github.com/jerryhcooke/smouldering_durtles/assets/30194403/a3baad23-955b-47b9-a113-b675f96a881d)

**Comment by patarapolw** [comment] 2023-05-12 01:02
@jerryhcooke Editing search engine works in Android Studio, but on clicking Cancel or outside the dialog, the overlay still remains.

Need one more click on the darken overlay to remove it.

**Comment by jerryhcooke** [comment] 2023-05-12 01:17
Can confirm that myself too - I'll pop that in the backlog to deal with, as it's primarily cosmetic and people won't be changing their search engines frequently, but will still aim to resolve 👍🏻

**Comment by jerryhcooke** [comment] 2023-05-18 08:36
This has been resolved in the v1.0.4 release

**Closed by jerryhcooke** 2023-05-18 08:36 UTC
Labels: bug
