### ISSUE TITLE
Set keyboard language hint to X for Y options missing in latest version

### ISSUE THREAD

**Issue by shocklateboy92** [jerryhcooke/smouldering_durtles#60] opened 2023-11-08 10:38 UTC
(These are the two options that I noticed - others may be missing too).

This is latest `main`.
![missing-options](https://github.com/jerryhcooke/smouldering_durtles/assets/856493/cf301fb3-825a-4e36-b927-ce867b27f516)

And here's the same page when I revert commit [29cc00e](https://github.com/jerryhcooke/smouldering_durtles/commit/29cc00ec8d230fff962c34581faeb41920ef1b6d):
![with-options](https://github.com/jerryhcooke/smouldering_durtles/assets/856493/de3bcaee-e1d6-4ae5-95fa-d411815e9a99)

which is what led me to suspect it's to do with putting those unrelated code changes in the `setVisibility()` method.
I'm unblocked locally with that fix, so I'm happy to close #58 and wait for you to investigate and fix @jerryhcooke :slightly_smiling_face:

**Comment by jerryhcooke** [comment] 2023-11-08 12:04
Have resolved this, the error was indeed caused by improper nesting of my new bits inside the setVisibility() method, will merge my revision in once tested a bit more

**Comment by shocklateboy92** [comment] 2023-11-12 06:56
Awesome! Thanks for the fix. Have you pushed it somewhere? I didn't see any commits that touch the file.

PS: Sorry for assuming it's corrupted code and trying to revert the whole file 😅

**Comment by hummusw** [comment] 2024-01-13 00:58
I'm able to see the language hint options in v1.1.0 now, are you still running into this issue on your end?

**Comment by jerryhcooke** [comment] 2024-01-13 07:46
Believe this was related to the theme switching fix that 1.1.0 resolved, so closing, but let me know if you experience anything similar ☺️

**Closed by jerryhcooke** 2024-01-13 07:46 UTC
Labels: bug
