### ISSUE TITLE
Lesson filter advanced settings shows grey box

### ISSUE THREAD

**Issue by lsuttle** [jerryhcooke/smouldering_durtles#8] opened 2023-05-12 04:48 UTC
Pixel4a, just downloaded 1.0.1 to try it out. When I try to click any of the filters under lesson advanced settings, I get a grey screen with no popup. 

 I do not get the same behavior with flaming durtles if that is useful. 

![Screenshot_20230512-004557](https://github.com/jerryhcooke/smouldering_durtles/assets/7538079/553ac5de-7b75-44fe-97e9-242003db27d6)

**Comment by jerryhcooke** [comment] 2023-05-12 12:35
Thanks for reporting, I suspect this is related to #5 which is what I fixed yesterday regarding the search engine prompt, I suspect I apply the same fix here 🤞🏻

**Comment by jerryhcooke** [comment] 2023-05-12 14:24
Have resolved this issue with the [v1.0.2 beta ](https://github.com/jerryhcooke/smouldering_durtles/releases/tag/v1.0.2b) which you can now download, there's still an issue with a grey overlay layer remaining after the dialog is closed, until it's tapped at least once. I'm having trouble narrowing down the cause, but will be resolved in the final v1.0.2 build. 

Closing this issue as already have one open for the grey overlay.

**Closed by jerryhcooke** 2023-05-12 14:24 UTC
Labels: bug
